// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzLys7loflzpDegoeb8IH2zuHvLGoPu7o',
    appId: '1:681494236609:android:8566e6233322615a35f340',
    messagingSenderId: '681494236609',
    projectId: 'lip-reading-b0adc-1d225',
    storageBucket: 'lip-reading-b0adc-1d225.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKRjdyl4pHfCzst_Pv5VTZzzN5Q5NpiRA',
    appId: '1:681494236609:web:09fa4f1b4d34422d35f340',
    messagingSenderId: '681494236609',
    projectId: 'lip-reading-b0adc-1d225',
    authDomain: 'lip-reading-b0adc-1d225.firebaseapp.com',
    storageBucket: 'lip-reading-b0adc-1d225.appspot.com',
    measurementId: 'G-E53WGXDCCG',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBy3jgB-CrCS1xYYJril8-64ovijF-k2A',
    appId: '1:681494236609:ios:42028ae67bec0fe935f340',
    messagingSenderId: '681494236609',
    projectId: 'lip-reading-b0adc-1d225',
    storageBucket: 'lip-reading-b0adc-1d225.appspot.com',
    iosBundleId: 'com.example.lipReading',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBy3jgB-CrCS1xYYJril8-64ovijF-k2A',
    appId: '1:681494236609:ios:42028ae67bec0fe935f340',
    messagingSenderId: '681494236609',
    projectId: 'lip-reading-b0adc-1d225',
    storageBucket: 'lip-reading-b0adc-1d225.appspot.com',
    iosBundleId: 'com.example.lipReading',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKRjdyl4pHfCzst_Pv5VTZzzN5Q5NpiRA',
    appId: '1:681494236609:web:7468096ebf61ce6135f340',
    messagingSenderId: '681494236609',
    projectId: 'lip-reading-b0adc-1d225',
    authDomain: 'lip-reading-b0adc-1d225.firebaseapp.com',
    storageBucket: 'lip-reading-b0adc-1d225.appspot.com',
    measurementId: 'G-ZXKP91QEXP',
  );

}